### ISSUE TITLE
Some words turned out to be unexpected level 

### ISSUE THREAD

**Issue by sei0158** [Maximax67/cefrpy#1]
Hello, 
I'm interested in predicting CEFR levels, so I've been playing around with this package (thanks for creating it). I found that some words were classified at unexpected levels, as follows:
I believe both words, 'figment' and 'tenacious,' are higher-level than A1. If you have any ideas, please let me know. ( I have confirmed that it can be reproduced on the Hugging Face demo. )
Thank you for your cooperation. 

Regards, 
Sei, 

### Environments
Windows 10, Python 3.10.11, IPython 8.28.0 
and
https://huggingface.co/spaces/Maximax67/cefrpy-demo

### Code (from the Usage example of this package)
from cefrpy import CEFRAnalyzer
analyzer = CEFRAnalyzer()

word = 'tenacious'
word = 'figment'
average_level = analyzer.get_average_word_level_float(word)
if average_level is not None:
    print(f"The average level of '{word}' is: {average_level}")
else:
    print(f"Average level not found for '{word}'.")

\# You can also get the average level in CEFR format
cefr_average_level = analyzer.get_average_word_level_CEFR(word)
if cefr_average_level is not None:
    print(f"The CEFR average level of '{word}' is: {cefr_average_level}")
else:
    print(f"CEFR average level not found for '{word}'.")
### Results for 'figment'
In [3]: run cefrpy-get-avarage-level-word.py
The average level of 'figment' is: 1.38
The CEFR average level of 'figment' is: A1
### Results for 'tenacious' 
In [4]: run cefrpy-get-avarage-level-word.py
The average level of 'tenacious' is: 1.0
The CEFR average level of 'tenacious' is: A1

**Comment by Maximax67** [comment]
Hi. The CEFR word difficulty calculations are based on word frequencies extracted from Google Ngrams and existing CEFR datasets. To determine the difficulty of words, I rely on their base forms using lemmatization and stemming algorithms. While these algorithms are usually practical, they are not 100% accurate. This leads to the kind of issue you have.

For example, in my [repository](https://github.com/Maximax67/Words-CEFR-Dataset) with parsed words dataset, the word tenacious (id: 29138) was incorrectly processed. Its stem form was mapped to "ten" (stem_word_id: 809), which has an A1 level. Such cases can happen, but overall, in most words, my approach is accurate. There are 172782 words in the dataset, so manually checking all of them is very tedious. The tradeoff is that we rely on algorithms that perform well in most cases but may misclassify certain words.

Currently, I am not planning to fix this issue, but I may address it in the future. Thank you for pointing this out.

**Comment by sei0158** [comment]
Hi, 
Thank you for your response. I think I can understand what you explained to me. For instance, in the following paper, it says that lemmatization was performed to calculate the frequencies of words. 
/***
http://www.lrec-conf.org/proceedings/lrec2018/pdf/439.pdf
Excerpts from this paper:
the corpus had to be lemmatized... (omitted)
Counting inflected forms entails that words having numerous inflected forms, such as verbs, would have their overall probability split between their different forms. 
***/

I believe that what you mean by 'lemmatization and stemming algorithms' is (roughly) similar to the idea presented in the paper. Thank you for your informative explanation. I want to keep learning English vocabulary with this package. Please close this issue. 

Regards,
Sei
